# Generated by Django 5.2.10 on 2026-01-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifferentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
