# Generated by Django 5.2.10 on 2026-01-30 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_imagebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='book.book'),
        ),
    ]
