# Generated by Django 5.2.10 on 2026-01-30 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_imagebook_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image_query', to='book.book'),
        ),
    ]
