# Generated by Django 5.2.10 on 2026-01-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_imagebook_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagebook',
            options={'verbose_name': 'Images of Book'},
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('SC', 'Science'), ('FN', 'Fun'), ('HC', 'Historical')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='imagebook',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Image Name'),
        ),
    ]
