# Generated by Django 6.0.2 on 2026-02-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_delete_differentbook_book_added_book_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='added',
            new_name='added_by',
        ),
    ]
