# Generated by Django 6.0.2 on 2026-02-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_rename_added_book_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='added_by',
            new_name='added',
        ),
    ]
