# Generated by Django 6.0.2 on 2026-02-12 06:54

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers_user_is_admin_user_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.CustomUserManager()),
                ('All_Objects', user.models.AllObjectsUsersManager()),
            ],
        ),
    ]
