# Generated by Django 6.0.2 on 2026-02-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view_deleted_user', 'Can view deleted users'), ('can_edit', 'Can edit users'))},
        ),
    ]
