# Generated by Django 6.0.2 on 2026-02-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_view_all_books', 'Can view all books'), ('can_view_published_books', 'Can view published books'))},
        ),
    ]
